[package]
name = "fudgegoggle"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
rqrr = "0.4"
prost = "0.9"
base64 = "0.13"
base32 = "0.4"
urlencoding = "1"

[dev-dependencies]
image = "0.23"
